name: Auto release excalidraw preview
on:
  push:
    branches:
      - master

jobs:
  Auto-release-excalidraw-preview:
    permissions:
      contents: read
      packages: write
    name: Auto release preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          registry-url: https://npm.pkg.github.com/
      - name: Auto release preview
        id: "autorelease"
        run: |
          yarn add @actions/core
          yarn autorelease ${{ github.sha }}
          yarn --cwd ./src/packages/excalidraw publish --tag preview
        env:
            NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
